### PR TITLE
fix(otlp): respect URL scheme in OTEL_EXPORTER_OTLP_ENDPOINT

### LINKED ISSUE #142: Exporter endpoint env var repeats scheme in mergeFromEnvMap
Per [spec](https://opentelemetry.io/docs/specs/otel/protocol/exporter/#endpoint-urls-for-otlphttp), `OTEL_EXPORTER_OTLP_ENDPOINT` is a URL (e.g. `http://localhost:4318`). The SDK treats it as `host:port` and re-prepends the scheme, producing a malformed URL.

**Repro:**

```sh
export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318
export OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
# run any trace exporter
```

```
error(otlp): failed to send payload: error.InvalidPort
```

**Root cause:**

[`mergeFromEnvMap`](https://github.com/zig-o11y/opentelemetry-sdk/blob/main/src/otlp.zig#L254) copies the env value verbatim into `self.endpoint`, then [`httpUrlForSignal`](https://github.com/zig-o11y/opentelemetry-sdk/blob/main/src/otlp.zig#L294) does `scheme ++ "://" ++ endpoint ++ path`, yielding `http://http://localhost:4318/v1/traces`.

The existing test uses `something:1234` (scheme-less), so the spec form isn't covered.

**Fix:** strip `http://` / `https://` on env ingest and set `self.scheme` accordingly. Happy to PR if that's the direction you'd take — or I could make `endpoint` store a full URL end-to-end if you'd rather refactor.

### PR DESCRIPTION
**Pull request by ChrisDBaldwin**
## Summary

Closes #142.

`OTEL_EXPORTER_OTLP_ENDPOINT` is specified as a URL (e.g. `http://localhost:4318`), but `mergeFromEnvMap` was copying the value verbatim into `ConfigOptions.endpoint`. `httpUrlForSignal` then prepends `scheme ++ "://"`, producing malformed URLs like `http://http://localhost:4318/v1/traces` and failing with `error.InvalidPort`.

## Fix

Extracted a small `setEndpointFromUrl` helper that parses the raw env value through `std.Uri` when a `://` is present, classifies the scheme into `self.scheme`, and stores the remainder (`host[:port][/path]`) in `self.endpoint`. This keeps the existing shape of `endpoint` intact so `httpUrlForSignal` needs no changes. Bare `host:port` values continue to flow through unchanged for compatibility with the existing test case.

Behaviors covered:

- Spec-form URLs: `http://localhost:4318` → `http://localhost:4318/v1/traces`
- Case-insensitive scheme match (RFC 3986): `HTTPS://host:4318`
- Path prefix preservation (per spec): `http://host:4318/mycollector` → `http://host:4318/mycollector/v1/traces`
- Multiple trailing slashes trimmed via `std.mem.trimRight`
- Empty-host-after-strip (e.g. `http://`) rejected with `ConfigError.InvalidEndpoint`
- Non-http/https schemes rejected with `ConfigError.InvalidScheme`
- Legacy bare `host:port` form preserved

The previously unused `const Uri = std.Uri` import at the top of the file is now load-bearing.

## Test plan

- [x] New table-driven test `otlp config from env with URL scheme in endpoint` covers all cases above
- [x] Existing `otlp config from env` test (bare `host:port`) still passes
- [x] `zig build test` — 284/285 passing; the one failing test (`OTLPExporter basic functionality` expecting `ConnectionRefused`) is pre-existing on `main` and unrelated to this change

### CODE REVIEW

**Comment by inge4pres** [comment]
Great work here @ChrisDBaldwin 👍🏼 
Thanks for this contribution 🙇🏼

File: src/otlp.zig [hunk 1]
```diff
@@ -278,6 +276,26 @@ pub const ConfigOptions = struct {
...
+            const Scheme = @FieldType(ConfigOptions, "scheme");
+            self.scheme = std.meta.stringToEnum(Scheme, lower) orelse return ConfigError.InvalidScheme;
+            value = raw[uri.scheme.len + "://".len ..];
+        }
+        value = std.mem.trimRight(u8, value, "/");
+        if (value.len == 0) return ConfigError.InvalidEndpoint;
+        const owned = try self.allocator.dupe(u8, value);
+        if (self.endpoint_owned) self.allocator.free(self.endpoint);
+        self.endpoint = owned;
+        self.endpoint_owned = true;
```
Comment (inge4pres) [inline src/otlp.zig:296]: I think we can do better in ownership tracking, at the same time this is not a new pattern for the otlp config layer.

**Review by inge4pres — APPROVED** [review]

File: src/otlp.zig (hunk 1 above)
Comment (ChrisDBaldwin) [reply src/otlp.zig:296]: I agree. Maybe an enum or something.
`self.endpoint_owned` could probably be calculated by `self.endpoint.ptr` rather than having the Boolean.
