### PR TITLE
fix(otlp): http/json format correctly serialized

### LINKED ISSUE #124: Testing: add integration test for `.http_json`
**Describe the current status**

Integration tests only cover the http/protobuf payloads sent from the SDK into the collector.

**Describe the desired state**

Add integration tests to ship also http/json format and validate the received content.

Related bug with zig-protobuf: https://github.com/Arwalk/zig-protobuf/issues/147

### PR DESCRIPTION
**Pull request by inge4pres**
Closes #124 

We add an integration test to validate that the `otlp` implementation works correctly with http/json payloads.

We know it doesn't, and an upgrade in dependency fixes it.

### CODE REVIEW

File: integration_tests/metrics_http_json.zig [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+        }
+        return err;
+    };
+    defer allocator.free(json_content);
+
+    std.debug.print("  ✓ Collector parsed http/json payload and wrote metric 'test_counter_http_json'\n", .{});
+
+    // Also confirm the string attribute value arrived — this is the oneof field
+    // that was previously mis-serialized.
+    if (std.mem.indexOf(u8, json_content, "http_json") != null) {
```
Comment (kmos) [inline integration_tests/metrics_http_json.zig]: Should be this check an assertion?

File: src/otlp.zig [hunk 2]
```diff
@@ -129,10 +130,7 @@ pub const Signal = enum {
                 .http_json => {
                     switch (self) {
                         inline else => |data| {
-                            var list: std.ArrayList(u8) = .empty;
-                            try list.ensureTotalCapacity(allocator, 4096);
-                            try list.writer(allocator).print("{f}", .{std.json.fmt(data, .{})});
-                            return try list.toOwnedSlice(allocator);
+                            return try protobuf.json.encode(data, .{}, .{ .emit_oneof_field_name = false }, allocator);
```
Comment (inge4pres) [inline src/otlp.zig]: This is the core of the fix,only possible when the zig-protobuf version supports it (likely v4, but now it's only available in HEAD of master branch)

**Review by kmos — APPROVED** [review]
